webtalk_init -webtalk_dir /home/kent/Source/School/CacheControlFSM_DDV3101Project/src/DDV3101Project_CacheControlFSM.sim/sim_1/behav/xsim/xsim.dir/TopBlock_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Sep 30 19:17:38 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "5518d2db-d324-467d-afc9-2d6f3cefd459" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "910112f0395d475cb25914e0fce68a29" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "146" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 20.04.1 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2905.945 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "13" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "42 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "66 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "11" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "10" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "2.30_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "227288_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1781970867 -regid "" -xml /home/kent/Source/School/CacheControlFSM_DDV3101Project/src/DDV3101Project_CacheControlFSM.sim/sim_1/behav/xsim/xsim.dir/TopBlock_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/kent/Source/School/CacheControlFSM_DDV3101Project/src/DDV3101Project_CacheControlFSM.sim/sim_1/behav/xsim/xsim.dir/TopBlock_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/kent/Source/School/CacheControlFSM_DDV3101Project/src/DDV3101Project_CacheControlFSM.sim/sim_1/behav/xsim/xsim.dir/TopBlock_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
